#!/usr/bin/env python3
"""Generate the Agent Buddy mascot: draws a cute robot, saves a PNG and a
C header (PNG bytes) for embedding in the ESP32 firmware.

Output:
  ../assets/mascot.png      (reference preview)
  ../src/mascot_png.h       (const uint8_t mascot_png[] for LovyanGFX drawPng)

All coordinates are in 240x320 display space, multiplied by S for smooth
supersampled rendering, then downscaled.
"""
import os
from PIL import Image, ImageDraw, ImageFont

W, H = 240, 320
S = 3                      # supersample factor
w, h = W * S, H * S

def s(v): return int(v * S)

img = Image.new("RGB", (w, h))
d = ImageDraw.Draw(img, "RGBA")

# ---- background: vertical teal gradient ----
top, bot = (16, 38, 54), (7, 17, 25)
for y in range(h):
    t = y / h
    d.line([(0, y), (w, y)],
           fill=(int(top[0]+(bot[0]-top[0])*t),
                 int(top[1]+(bot[1]-top[1])*t),
                 int(top[2]+(bot[2]-top[2])*t)))

CX = 120
ACCENT = (47, 184, 230)
LIGHT  = (234, 246, 252)
INK    = (19, 32, 43)

def rr(x0, y0, x1, y1, r, **kw):
    d.rounded_rectangle([s(x0), s(y0), s(x1), s(y1)], radius=s(r), **kw)
def ell(x0, y0, x1, y1, **kw):
    d.ellipse([s(x0), s(y0), s(x1), s(y1)], **kw)

# ---- antenna ----
d.line([(s(CX), s(58)), (s(CX), s(34))], fill=ACCENT, width=s(4))
ell(CX-9, 16, CX+9, 34, fill=(255, 210, 80))
ell(CX-4, 19, CX+1, 24, fill=(255, 245, 190))           # glint

# ---- head ----
rr(40, 58, 200, 196, 42, fill=LIGHT, outline=ACCENT, width=s(4))

# ---- eyes ----
for ex in (95, 145):
    ell(ex-20, 96, ex+20, 146, fill=INK)
    ell(ex-11, 104, ex+1, 120, fill=(255, 255, 255))     # big shine
    ell(ex+6, 130, ex+13, 139, fill=(210, 225, 235))     # small shine

# ---- cheeks ----
for cxx in (78, 162):
    ell(cxx-11, 150, cxx+11, 168, fill=(255, 150, 162, 160))

# ---- smile ----
d.arc([s(96), s(132), s(144), s(180)], start=20, end=160, fill=INK, width=s(5))

# ---- body ----
rr(70, 196, 170, 282, 26, fill=ACCENT)
# arms (behind body edges)
ell(54, 210, 80, 238, fill=LIGHT)
ell(160, 210, 186, 238, fill=LIGHT)
# chest screen with code glyph
rr(88, 210, 152, 252, 9, fill=(10, 24, 34))
try:
    fbig = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", s(22))
    fsm  = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", s(15))
except Exception:
    fbig = ImageFont.load_default(); fsm = fbig
d.text((s(CX), s(231)), "</>", font=fbig, fill=ACCENT, anchor="mm")
# feet
rr(90, 278, 112, 296, 7, fill=INK)
rr(128, 278, 150, 296, 7, fill=INK)

# ---- title ----
d.text((s(CX), s(308)), "Agent Buddy", font=fsm, fill=LIGHT, anchor="mm")

# ---- downscale ----
img = img.resize((W, H), Image.LANCZOS)

base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.makedirs(os.path.join(base, "assets"), exist_ok=True)
png_path = os.path.join(base, "assets", "mascot.png")
img.save(png_path, optimize=True)
data = open(png_path, "rb").read()
print(f"PNG: {png_path}  ({len(data)} bytes)")

hdr = os.path.join(base, "src", "mascot_png.h")
with open(hdr, "w") as f:
    f.write("#pragma once\n#include <stdint.h>\n")
    f.write("// Auto-generated by tools/make_mascot.py — Agent Buddy mascot (PNG)\n")
    f.write(f"const uint32_t mascot_png_len = {len(data)};\n")
    f.write("const uint8_t mascot_png[] = {\n")
    for i in range(0, len(data), 16):
        f.write("  " + ",".join(str(b) for b in data[i:i+16]) + ",\n")
    f.write("};\n")
print(f"Header: {hdr}")
