"""
Convert sprite-sheet-alpha.png + manifest.json → buddy_sprite.h (C array for ESP32).

Each pixel stored as uint16_t RGB565; alpha=0 pixels stored as TRANSPARENT_KEY (0x0001).
Frame layout stored as compile-time constants matching manifest animation.rows.
"""

import json, struct, sys
from pathlib import Path
from PIL import Image

TRANSPARENT_KEY = 0x0001   # near-black; treated as transparent by blit function

def rgba_to_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def convert(run_dir: Path, out_h: Path):
    atlas = Image.open(run_dir / "sprite-sheet-alpha.png").convert("RGBA")
    with open(run_dir / "manifest.json") as f:
        mf = json.load(f)

    anim = mf["animation"]
    cell_w = anim["cellWidth"]
    cell_h = anim["cellHeight"]
    cols   = anim["columns"]
    rows   = anim["rows"]

    W, H = atlas.size
    pixels = list(atlas.getdata())  # type: ignore[attr-defined]

    # build flat RGB565 array row-major
    rgb565 = []
    for y in range(H):
        for x in range(W):
            r, g, b, a = pixels[y * W + x]
            if a < 128:
                rgb565.append(TRANSPARENT_KEY)
            else:
                v = rgba_to_rgb565(r, g, b)
                rgb565.append(v if v != TRANSPARENT_KEY else 0x0002)

    # state index mapping in order
    state_order = list(rows.keys())   # idle, coding, talking, success

    lines = [
        "// Auto-generated by atlas_to_c.py — do not edit",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define SPRITE_CELL_W  {cell_w}",
        f"#define SPRITE_CELL_H  {cell_h}",
        f"#define SPRITE_COLS    {cols}",
        f"#define SPRITE_ROWS    {len(state_order)}",
        f"#define SPRITE_W       {W}",
        f"#define SPRITE_H       {H}",
        f"#define SPRITE_TRANSPARENT 0x{TRANSPARENT_KEY:04X}U",
        "",
        "// State indices",
    ]
    for i, st in enumerate(state_order):
        lines.append(f"#define SPRITE_ST_{st.upper():10s} {i}")
    lines += [
        "",
        "struct SpriteAnim {",
        "    uint8_t row;",
        "    uint8_t frames;",
        "    uint8_t fps;",
        "    bool    loop;",
        "};",
        "",
        f"static const SpriteAnim SPRITE_ANIMS[{len(state_order)}] = {{",
    ]
    for st in state_order:
        r = rows[st]
        lines.append(f"    {{ {r['row']}, {r['frames']}, {r['fps']}, {'true' if r['loop'] else 'false'} }},  // {st}")
    lines += [
        "};",
        "",
        f"// {W}x{H} atlas, RGB565, SPRITE_TRANSPARENT marks alpha",
        f"// Total: {len(rgb565)*2} bytes ({len(rgb565)*2//1024} KB)",
        f"static const uint16_t SPRITE_ATLAS[{len(rgb565)}] PROGMEM = {{",
    ]

    # emit 16 values per line
    for i in range(0, len(rgb565), 16):
        chunk = rgb565[i:i+16]
        lines.append("    " + ", ".join(f"0x{v:04X}" for v in chunk) + ",")

    lines += ["};", ""]
    out_h.write_text("\n".join(lines))
    kb = len(rgb565) * 2 / 1024
    print(f"Written {out_h}  ({W}x{H}, {kb:.1f} KB)")


if __name__ == "__main__":
    run_dir = Path(__file__).parent / "buddy-dino"
    out_h   = Path(__file__).parent.parent.parent / "src" / "buddy_sprite.h"
    convert(run_dir, out_h)
